site_name: b0nyo
theme:
  name: material
  palette:
    # Tema oscuro predeterminado
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark

    # Tema claro opcional
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light
